### PR TITLE
musl fixes

### PR DESCRIPTION
**Pull request by Duncaen**

### CODE REVIEW

**Comment by kristapsdz** [comment]
I'll put in the ap/NULLs, but I need more information on the headers you're shuffling around.  Which functions require which header changes?

**Comment by Duncaen** [comment]
This is from compiling slant with musl libc, `ctype.h` for `isspace` used in `b64_pton`,`sys/types.h` for `size_t` and `stdint.h` for `int64_t`.

**Comment by kristapsdz** [comment]
I think the current checkins fix this.  Let me know if they do for you!  I'm tagging out a release, but that's for unrelated functionality.  (String concatenation operator.)

**Comment by Duncaen** [comment]
Thanks, one small issue building the generated json.c/db.c files on a armv7 musl machine is using the `u_char` typedef, which is only defined in `sys/types.h`.

**Comment by kristapsdz** [comment]
Last commit should fix this, no?  If it does, I'll tag out along with some other small changes.

**Comment by Duncaen** [comment]
Yes build without issues now, thanks.

**Comment by kristapsdz** [comment]
Part of the newest version, thank you so much!  By the way, if you don't want to pull a non-standard sys/queue.h into your include directory, you can always patch the system to do what it does with the base64 code except with sys/queue.h.  (oconfigure has a version you can use.)

**Pull request closed without merging**
